### ISSUE TITLE
Hard to reuse RPC handler functions on server side code.

### ISSUE THREAD

**Issue by lixin9311** [bufbuild/connect-go#301]
**Is your feature request related to a problem? Please describe.**

When using the vanilla grpc-go, it is easy to reuse other RPC handler functions.
For instance:
```go
type Server struct{}

func (s *Server) RpcCallA(ctx context.Context, req *pb.RpcCallARequest) (*emptypb.Empty, error) {
    // typically I would like to use a type switch on a oneof field
    // all metadata are passed and preserved in ctx
    return s.RpcCallB(ctx, req.GetSomeField())
}
func (s *Server) RpcCallB(ctx context.Context, req *pb.RpcCallBRequest) (*emptypb.Empty, error) {
    // actual handling codes
}
```

But with the connect-go implementation of server handlers, if I apply a similar pattern, it is not easy to preserve the request metadata.

```go
type Server struct{}

func (s *Server) RpcCallA(ctx context.Context, req *connect_go.Request[pb.RpcCallARequest]) (*connect_go.Response[emptypb.Empty], error) {
    // typically I would like to use a type switch on a oneof field
    // all metadata will be lost. It is possible to manually clone the headers. But the Spec is passed by value.
    return s.RpcCallB(ctx, connect_go.NewRequest(req.Msg.GetSomeField()))
}
func (s *Server) RpcCallB(ctx context.Context, req *connect_go.Request[pb.RpcCallBRequest]) (*connect_go.Response[emptypb.Empty], error) {
    // actual handling codes
}
```

**Describe the solution you'd like**
What would you like to have `connect-go` do? How should we solve the problem?

If request can provide an extra method, e.g. `func (r *Request[_]) Clone[T any](msg *T) *connect_go.Request[T]`,
enabling copy/clone the metadata of the incoming request would be great.

Even better if we could have an extra method to set the header directly.
```go
header := req.Header.Clone()
req := connect_go.NewRequest(foo)
req.WithHeader(header)
```

**Comment by pkwarren** [comment]
@lixin9311 - would you also expect to have a `WithSpec(spec)` method?

From the example, it seems like you might want to change Spec.Procedure from '/someservice/RpcCallA' to '/someservice/RpcCallB'?

**Comment by lixin9311** [comment]
> @lixin9311 - would you also expect to have a `WithSpec(spec)` method?
> 
> From the example, it seems like you might want to change Spec.Procedure from '/someservice/RpcCallA' to '/someservice/RpcCallB'?

Yes, absolutely sure!

**Comment by jhump** [comment]
FWIW, I think having one RPC method directly invoke another this way can be error-prone. The main issue I've seen is if your handler assumes that invariants were checked by an interceptor. When you invoke another method that way, no interceptors are being run. If the invariant checks differ from `RpcCallA` to `RpcCallB` (such as running validators on the request/response messages, or performing an authz check that differs between the two), this could cause bugs.

Alternatives:
1. Put the shared code into a separate unexported method on the server struct that both `RpcCallA` and `RpcCallB` can call. This could accept the request message and headers as separate arguments, so it's easy to explicitly pass the same headers if desired. This is for the case where you really _don't_ want the interceptors to run again. This is the most straight-forward idiom IMO for sharing code between two RPC methods, instead of having one method directly invoke the other.
2. Use an in-process transport, which then goes through all interceptors (and does any extra invariant checks, like request validation or authz). I don't think connect-go provides an in-process transport, so maybe that's worth filing as a separate issue? For gRPC, there are two options:

      * [google.golang.org/grpc/test/bufconn](https://pkg.go.dev/google.golang.org/grpc/test/bufconn): This still uses the entire HTTP/2-based protocol. But the client and server communicate via channels instead of using a network socket.
      * [github.com/fullstorydev/grpchan/inprocgrpc](https://pkg.go.dev/github.com/fullstorydev/grpchan/inprocgrpc): This also uses channels to send data between and client and server. It's a little more efficient than the one above, uses buffered channels as the back-pressure mechanism (instead of HTTP/2 flow control), and doesn't require serialization/de-serialization of messages.

      This has the added benefit that invoking a streaming RPC is _way_ easier when using a client stub, vs. trying to directly invoke the other server method. It does require some way to add headers to a new request, though, as per the thrust of this issue.

**Comment by akshayjshah** [comment]
@jhump is on point.

* The first option he outlined is what most users want, and it clarifies when you should expect interceptors to run.
* If you'd rather use an in-process transport (option 2 above), you can easily build one yourself using the standard library's `net.Pipe` - `connect-go` includes an [unexported one](https://github.com/bufbuild/connect-go/blob/main/example_init_test.go#L44) for use in examples.

At least for now, I'd rather avoid expanding `connect-go`'s exported API as you suggest.
