### ISSUE TITLE
How can i use with google.rpc.Status?

### ISSUE THREAD

**Issue by xdorro** [bufbuild/connect-go#327]
**Is your feature request related to a problem? Please describe.**
I had a problem when buff generate after importing "google/rpc/status.proto", the generated code did not understand my library.

My english is not very good, but something like when i import proto from outside and then run buf generate, the following code generated got error about path to package
```
syntax = "proto3";

package user.v1;

import "google/rpc/status.proto";

service UserService {
  rpc DeleteUser (UUIDRequest) returns (google.rpc.Status) {}
}
```

**Describe the solution you'd like**
I want when import "google/rpc/status.proto" path will look like "google.golang.org/grpc/status" or similar instead of "github.com/example/proto-gen-go/google/rpc"

**Describe alternatives you've considered**
We can see how to handle it like grpc-gateway (https://github.com/grpc-ecosystem/grpc-gateway)

**Comment by akshayjshah** [comment]
It looks like you're trying to write a `DeleteUser` RPC that doesn't have a response message - it just succeeds or fails. (That is, the Go function signature would be `func DeleteUser(id uuid.UUID) error`.) Is that right?

If so, your protobuf schema isn't quite right. Google's `Status` message is always part of every gRPC or Connect error, so you don't include it in the schema. Instead, you're probably looking for this:

```protobuf
syntax = "proto3";

package user.v1;

import "google/protobuf/empty.proto";

service UserService {
  rpc DeleteUser (UUIDRequest) returns (google.protobuf.Empty) {}
}
```

`google.protobuf.Empty` is one of the [well-known types](https://visualstudiomagazine.com/articles/2020/01/16/grpc-well-known-types.aspx), so it gets handled specially during code generation. `google.rpc.Status` is _not_ one of the well-known types, despite appearing often in gRPC.

Keep in mind that the way you're doing this is very inflexible - _any_ changes in requirements will break backwards compatibility, because adding request or response data will require changing the message types. It's a bit more verbose, but this is much safer:

```protobuf
syntax = "proto3";

package user.v1;

message DeleteUserRequest {
  string uuid = 1; // or however you want to represent UUIDs
}

message DeleteUserResponse {}

service UserService {
  rpc DeleteUser (DeleteUserRequest) returns (DeleteUserResponse) {}
}
```

**Comment by xdorro** [comment]
thank you very much
