### ISSUE TITLE
Map custom HTTP routes to connect handlers

### ISSUE THREAD

**Issue by hampusohlsson** [bufbuild/connect-go#368]
**Is your feature request related to a problem? Please describe.**
First of all, love what you guys are doing. Thanks for making the protobuf ecosystem better. We are currently in the process of migrating away from [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) to connect.

Since our application is already in use in production, we still need to support a bunch of legacy HTTP GET/POST rpc annotation routes on our connect server. So I was searching for an official way of doing a similar mapping from custom routes to the connect handler, but could not find any examples.

**Describe the solution you'd like**
I think I came up with a neat solution that works really well afaict, but **want to sanity check if it makes sense?** - and if you can spot any pitfalls with this method. 

I am adding custom routes on my http client, and setting up a reverse proxy to the connect handler:

```go
r.Post("/customroute/ping", proxy.To((server).Ping))
```

This is an example of server setup with the [chi/v5](https://github.com/go-chi/chi) router.

```go
type PingServer struct{}

func (s *PingServer) Ping(
	ctx context.Context,
	req *connect.Request[pb.PingRequest],
) (*connect.Response[pb.PingResponse], error) {
	return connect.NewResponse(&pb.PingResponse{}), nil
}

func main() {
	port := "8080"
	r := chi.NewRouter()

        server := &PingServer{}
	// Mount connect http.Handler
	basePath, httpHandler := pingv1connect.NewPingServiceHandler(server)
	r.Mount(basePath, httpHandler)

	// Create a reverse proxy for proxying HTTP requests -> connect handlers
	proxy := NewProxy(basePath, port)
	r.Post("/customroute/ping", proxy.To((server).Ping))

	// Listen and serve..
}
```
Where `Proxy` is implemented like this:
```go
type Proxy struct {
	target   *url.URL
	proxy    *httputil.ReverseProxy
	basePath string
}

func NewProxy(basePath, port string) *Proxy {
	target, _ := url.Parse(fmt.Sprintf("http://localhost:%s", port))
	return &Proxy{
		basePath: basePath,
		target:   target,
		proxy:    httputil.NewSingleHostReverseProxy(target),
	}
}

func (p *Proxy) To(connectHandler any) http.HandlerFunc {
	// Derive the proxy endpoint based off service name and handler name
	endpoint, _ := url.Parse(p.basePath + p.getFunctionName(connectHandler))
	return func(w http.ResponseWriter, r *http.Request) {
		r.Host = p.target.Host
		r.Method = http.MethodPost // <-- enforce POST
		r.URL = endpoint
		r.Header.Set("content-type", r.Header.Get("content-type"))
		p.proxy.ServeHTTP(w, r)
	}
}

func (p *Proxy) getFunctionName(fn any) string {
	fnPath := runtime.FuncForPC(reflect.ValueOf(fn).Pointer()).Name()
	parts := strings.Split(fnPath, ".")
        // strip -fm suffix in case handler is passed as `s.Handler` instead of `(s).Handler`
	return strings.TrimSuffix(parts[len(parts)-1], "-fm")
}
```

**Describe alternatives you've considered**
Have not tried any alternatives.

**Additional context**
N/A

**Comment by akshayjshah** [comment]
Hi @hampusohlsson! Sorry for the delay - I lost track of this issue right before Gophercon 😢 In the example you have above, the `Proxy.To` method has a few gotchas. Most importantly, it's not properly converting GET requests with URL parameters to POSTs - it changes the HTTP method, but doesn't convert the URL params to a JSON body. In general, it's pretty complicated to get this right without code generation.

If you're using grpc-gateway to support RESTful GETs today, I'd recommend continuing to do so until you can migrate all your clients to use the Connect protocol. (Because `connect-go` handlers support the gRPC protocol by default, they work with grpc-gateway out of the box. See https://github.com/johanbrandhorst/connect-gateway-example for an example.)

If you really want to get off grpc-gateway and you're willing to do GET -> POST data mapping yourselves, I'd replace `Proxy`  and build a `connect.Handler` yourself. In your example above, you can control routing by using `connect.NewUnaryHandler`:

```go
const customPath = "/customroute/ping"
customPingHandler := connect.NewUnaryHandler(customPath, server.Ping)
// If necessary, wrap customPingHandler to handle GETs or any other required payload transformations.
r.Post(customPath, customPingHandler)
```

That's both simpler and quite a bit more efficient, since you're not proxying requests over the network (even on localhost).

**Comment by hampusohlsson** [comment]
Thanks @akshayjshah ! Shortly after I posted this issue I realised the issue with GET params, so actually ended up implementing that transformation. Using `NewUnaryHandler()` right away seems more efficient indeed.

**Comment by akshayjshah** [comment]
Excellent!

**Comment by akshayjshah** [comment]
It could; it depends on the router you're using and its ability to handle these sorts of paths. Nearly all routers can work with `net/http` handlers, so something ought to be possible.
