### ISSUE TITLE
Marshal response using a different codec to request unmarshal

### ISSUE THREAD

**Issue by andrewweston** [bufbuild/connect-go#391]
**Is your feature request related to a problem? Please describe.**
I cannot (easily) customise response serialisation without also customising request serialisation. The particular issue I'm facing is the client (3rd-party client) sends a request with content-type "application/json" and expects a response with content-type "application/jwt".

**Describe the solution you'd like**
I would like to customise the marshalling of responses based on the response header rather than the request header. 

**Describe alternatives you've considered**
The code (protocol_connect.go) shows unmarshalling and marshalling are both handled by the same codec, which is set based on the request content-type header.
My current solution is to create a custom json codec and check the message type before determining how to marshal the response. This is not as clean as setting a response content-header and a single purpose ("application/jwt") codec that can be used to marshal responses.

**Additional context**
[Relevant section of code.](https://github.com/bufbuild/connect-go/blob/main/protocol_connect.go#L147-L151)

**Comment by akshayjshah** [comment]
The workaround you've got is the best that we can offer - even though it's a little unpleasant, I'm glad it's working for you!

We're not going to expose the functionality you're looking for because `connect-go` isn't a generic protobuf-over-HTTP package - it supports three specific RPC protocols (gRPC, gRPC-Web, and Connect). With one specific exception, all three protocols require that the Content-Type of requests and responses match.
