### ISSUE TITLE
Client-side streams takes 100K Send() calls before failing after server returns error

### ISSUE THREAD

**Issue by alecthomas** [bufbuild/connect-go#512]
**Describe the bug**

When the server side of a client stream returns an error, the Connect client does not report the error for ~100K subsequent Send() calls. The official gRPC client does not exhibit this behaviour.

From the observed behaviour it seems that the Connect client has some internal buffer that has to be exhausted before an error is returned, while the gRPC client errors as soon as the server does. The gRPC client code has a small sleep to highlight this.

I encountered this on a client-streaming endpoint that is used to periodically (every 2-5s) heartbeat to a server.

Example output of the Connect and gRPC clients. "sent N" is the number of Send() calls each client issues.

```
🐚 ~/dev/connect-bug $ go run ./cmd/connect-client
sent 107762
panic: aborted: an error

goroutine 1 [running]:
main.main()
	/Users/alec/dev/connect-bug/cmd/connect-client/main.go:22 +0x120
exit status 2
🐚 ~/dev/connect-bug $ go run ./cmd/grpc-client   
sent 2
panic: rpc error: code = Aborted desc = an error

goroutine 1 [running]:
main.main()
	/Users/alec/dev/connect-bug/cmd/grpc-client/main.go:29 +0x1a8
exit status 2
```

**To Reproduce**

I've attached a .zip file with a full reproduction (it also includes all of the versions of tools I'm using in a [Hermit](https://cashapp.github.io/hermit/) environment - `. ./bin/activate-hermit` to use this, or install the tools via other means).

1. Run the server in one terminal. `go run ./cmd/server`
2. Run connect client in another terminal: `go run ./cmd/connect-client`
3. Run gRPC client in another terminal: `go run ./cmd/grpc-client`

[connect-client-streaming-bug.zip](https://github.com/bufbuild/connect-go/files/11570649/connect-client-streaming-bug.zip)

**Comment by akshayjshah** [comment]
Hey @alecthomas! Thanks for taking a look at Connect - I've used `kingpin` for many command-line tools :)

The example you uploaded is very helpful in debugging. The problem is that the client is misconfigured: `http.DefaultClient` doesn't allow h2c connections, so even though you've got an h2c-capable server you end up with an HTTP/1.1 stream. Following https://connect.build/docs/go/deployment#h2c (or enabling TLS on the server) improves the behavior quite a bit - <100 messages before seeing the error, vs. thousands. Adding the same sleep you've got in the `grpc-go` code brings behavior to parity - you see the error sent by the server after sending two messages.

Unrelated to the specific behavior you're reporting, but possibly of interest, is that your example also has the client using Connect's own protocol instead of gRPC's protocol. If it's important to you that the client uses the gRPC protocol, use the `connect.WithGRPC` option. Either way, the changes above resolve the behavior you're seeing.

The Connect client code I ended up with looks like this:

```go
package main

import (
	"context"
	"crypto/tls"
	"fmt"
	"net"
	"net/http"
	"time"

	"github.com/alecthomas/connectbug"
	"github.com/alecthomas/connectbug/connectbugconnect"
	"golang.org/x/net/http2"
)

func newInsecureClient() *http.Client {
	return &http.Client{
		Transport: &http2.Transport{
			AllowHTTP: true,
			DialTLS: func(network, addr string, _ *tls.Config) (net.Conn, error) {
				return net.Dial(network, addr) // see docs for some notes about this :)
			},
		},
	}
}

func main() {
	client := connectbugconnect.NewBuggyServiceClient(
		newInsecureClient(),
		"http://127.0.0.1:8999",
		// connect.WithGRPC(),
	)
	stream := client.BuggyMethod(context.Background())
	sent := 0
	for {
		err := stream.Send(&connectbug.BuggyRequest{})
		sent++
		if err != nil {
			fmt.Println("sent", sent)
			_, err := stream.CloseAndReceive()
			panic(err)
		}
		time.Sleep(10 * time.Millisecond)
	}
}
```

Hope that helps! I'll keep this issue open for a few days (at least until after the US long weekend) in case there's any more discussion.

**Comment by akshayjshah** [comment]
Oh! If you're looking at client-side Connect behavior, you may want to follow #295 too. As part of that work, we're planning to make it easier and safer to create h2c-capable `net/http` clients.

**Comment by alecthomas** [comment]
Hey @akshayjshah, thanks for that and apologies for not RTFMing sufficiently. I actually read that page to set up the server with h2c, but must have blanked on the client-side 🤦 .

I did also try `WithGRPC()`, but it failed in the same way for what I now realise were the same reasons.

I'm really enjoying Connect, thanks. It is refreshingly straightforward code unlike the Google gRPC implementation, I _really_ love its use of the standard Go HTTP packages, and how it supports HTTP/1 out of the box. 

Speaking of that, has there been any thought to supporting the `api.http` annotations? Though thinking about it briefly, it could probably be implemented via HTTP middleware that takes the FileDescriptor containing a service, and remapping incoming requests.

PS. I'm happy to hear you're a Kingpin enjoyer :)

**Comment by akshayjshah** [comment]
> Speaking of that, has there been any thought to supporting the api.http annotations? Though thinking about it briefly, it could probably be implemented via HTTP middleware that takes the FileDescriptor containing a service, and remapping incoming requests.

I think you basically nailed it - I'm happy to have support live out in the ecosystem, but it doesn't need to be in `connect-go` itself.
